### ISSUE TITLE
The default line height is inconsistent among weights.

### ISSUE THREAD

**Issue by davmuse** [be5invis/Iosevka#43]
Hello,
I've noticed a difference in the default **line-height** between the styles [thin,extra-light, light, regular] and [medium, bold, heavy]. Is there a way to **normalise** these variants ? (i would prefer a mono-spaced and mono-line-height font)
Thanks

**Comment by be5invis** [comment]
In 1.4.3 the metrics in all variants and all weights are exactly same (1.25em by default).
Is it rounding error?

**Comment by davmuse** [comment]
This problem appears when I use the font in OSX Pages (Yosemite) ...

**Comment by be5invis** [comment]
@davmuse Have you tried to uninstall and reinstall the latest version?

**Comment by bitserf** [comment]
I decided to try this (latest HEAD, revision ce20e08), and I can reproduce the issue on OS X (El Capitan). It happens independently of app, it also happens in Terminal and TextEdit, not just Pages app:

It looks like extra space is at the top for some reason, see selection:

*Regular*
<img width="341" alt="regular" src="https://cloud.githubusercontent.com/assets/167841/11987494/47ba0252-aa45-11e5-902d-1854da2a03d7.png">

*Medium*
<img width="333" alt="medium" src="https://cloud.githubusercontent.com/assets/167841/11987495/56c81658-aa45-11e5-871d-0fe8d562926b.png">

The bottom looks the same amount of space.

I have no idea what could account for the difference - I compared Pragmata Regular and Bold on OS X and it has the same spacing, so there must be something different about the two weights that causes this, maybe not metrics.

**Comment by be5invis** [comment]
@bitserf So OSX calculates the default line height using something other than metrics?!
I'd like to figure out why. I'll build a variant with a character with extremely high ascender and low descender to determine whether the line height is decided by the maximum bounding box of the glyphs.

**Comment by be5invis** [comment]
@bitserf @davmuse I added a glyph (U+E09F) with extremely large bounding box. Is this version still suffering from line height inconsistency?
Download: http://7xpe0v.com1.z0.glb.clouddn.com/iosevka-test-lineheight-osx-20151224a.7z

**Comment by bitserf** [comment]
Here's another funny thing. I wrote a test application to render fonts for comparison, and it seems Safari corrects the baseline, so it must be something in Core Text (OS X text renderer). 

Test app:
https://gist.github.com/bitserf/ec3fc3ce76b8231dfa99

Result PDF:
[Iosevka-Regular-Bold.pdf](https://github.com/be5invis/Iosevka/files/71426/Iosevka-Regular-Bold.pdf)

I will try your updated font now.

**Comment by be5invis** [comment]
@bitserf I do not have any OSX machines (I use Windows and Linux), and the metrics on Windows are in well sync.

**Comment by bitserf** [comment]
@be5invis I tried your test line height files, and it still has the problem

**Comment by be5invis** [comment]
@bitserf Have you tried to clear the font cache after deleting the old versions?

**Comment by be5invis** [comment]
@bitserf @davmuse I tried another approach to set the metrics. Is the problem still there?

http://7xpe0v.com1.z0.glb.clouddn.com/iosevka-lineheight-test-osx-20151224b.7z

**Comment by bitserf** [comment]
@be5invis Deleting the fonts in Font Book, then emptying trash and installing new ones seem to work for me (other changes I have made always show up immediately).

The problem still happens with the 20151224b version as well.

I checked all of the weights:

*OK:*

-Regular
-Light
-Extralight
-Thin

*Extra space:*

-Medium
-Bold
-Heavy

**Comment by be5invis** [comment]
@bitserf Have you tried to clear the **font cache**?

Instructions:

> **Mac OS X 10.5 (Leopard) and later**
> * Close all applications.
> * Launch Terminal
> * Enter the following command at the prompt and press Return: atsutil databases -removeUser
> * Enter the following command at the prompt and press Return: atsutil databases -shutdown
> * Enter the following command at the prompt and press Return: atsutil databases -ping
> * Quit Terminal

**Comment by bitserf** [comment]
@be5invis I quit all applications, ran those commands:

<img width="725" alt="screen shot 2015-12-24 at 7 30 21 pm" src="https://cloud.githubusercontent.com/assets/167841/11990605/eb8edf4a-aa74-11e5-98c7-97cf4406f499.png">

Logged out and logged back in, but the problem still exists.

**Comment by be5invis** [comment]
@bitserf  I think it is a OSX problem...

**Comment by be5invis** [comment]
@bitserf @davmuse Does [this version](http://7xpe0v.com1.z0.glb.clouddn.com/iosevka-20151224c.7z) solve the problem?
I and @clerkma find out that OSX actually cares about the descender, maybe related to the "broken underline" feature introduced recently.

**Comment by be5invis** [comment]
@clerkma 's screenshot:
![snap](http://photo.weibo.com/2039445353/wbphotos/large/mid/3923606792634851/pid/798f7769gw1ezat4jke9bj21kw0g7dox)

**Comment by bitserf** [comment]
@be5invis Yes, it is fixed :beer: 

<img width="630" alt="screen shot 2015-12-24 at 9 07 55 pm" src="https://cloud.githubusercontent.com/assets/167841/11991724/8364214c-aa82-11e5-8fd6-1a63f77b7bd1.png">

I think the reporter for #42 should re-test with that version, it seems related?

**Comment by be5invis** [comment]
@bitserf Closed.

**Comment by bitserf** [comment]
@be5invis I updated my Gist https://gist.github.com/bitserf/ec3fc3ce76b8231dfa99, if @clerkma is interested for OS X testing.

It now uses Core Text to render font, and can be used to preview multiple fonts without installing them on OS X.

I tested it on the old TTFs, and it reproduced the problem, and on the new TTFs it is all aligned.

Gist needs Xcode 7.2 to compile, example usage:

```shell
λ /Users/ljb/Library/Developer/Xcode/DerivedData/FontPreview-dqtyplftknmmsgfgalkquwgrirbo/Build/Products/Debug/FontPreview Iosevka-Regular-Bold-1.5.0.pdf 14 ~/Code/Iosevka/build/iosevka-regular.ttf ~/Code/Iosevka/build/iosevka-bold.ttf
loading font /Users/ljb/Code/Iosevka/build/iosevka-regular.ttf using Core Text
loading font /Users/ljb/Code/Iosevka/build/iosevka-bold.ttf using Core Text
drawing text with font: Iosevka
drawing text with font: Iosevka-Bold
rendered 14186 byte(s) to PDF file Iosevka-Regular-Bold-1.5.0.pdf
```

The test app produced this PDF file:

[Iosevka-Regular-Bold-1.5.0.pdf](https://github.com/be5invis/Iosevka/files/71652/Iosevka-Regular-Bold-1.5.0.pdf)

Maybe this is useful for others? For me, it will be a *LOT* faster than installing/uninstalling font by hand every time.

**Comment by davmuse** [comment]
Hello, and HNY !
I've downloaded the lastest (1.6.1) version of the font. I cleared the cache. **It works a lot better** ... but I've found a strange behavior in Pages (I have not test elsewhere). 

The problem still exists using Iosevka (size <= 7pt) !! 

I first thought it was a Pages or OSX problem, but using differents fonts (like Courier) proves that there's still something strange in Iosevka ...

I'm sorry because I thought everything was OK. Unfortunally for me, I use 7pt font in my documents ... 

Thanks for everything ! 

![sc 2016-01-04 a 14 05 08](https://cloud.githubusercontent.com/assets/14543313/12090295/e0bc8c80-b2ed-11e5-8a23-eeaff4e7d089.jpg)

**Comment by be5invis** [comment]
**THIS IS AN OS X BUG**, see [discussions here](http://typedrawers.com/discussion/1301/the-default-line-height-in-osx-fontbook). You can try to decrease `hhea.ascent` to avoid this.

**Comment by davmuse** [comment]
Ok, thanks.

**Comment by be5invis** [comment]
@davmuse Since your problem is size-specific, maybe related to rounding I think.

**Comment by davmuse** [comment]
Sorry, but you're talking chinese to me ... :)
I'll see later ...
